# Generated by Django 5.1.6 on 2025-02-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('intro', models.TextField()),
                ('custom_header_html', models.TextField(blank=True, help_text='Add custom HTML/Javascript for header', null=True)),
                ('custom_body_html', models.TextField(blank=True, help_text='Add custom HTML/Javascript for footer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('index', models.BooleanField(default=True)),
                ('status', models.BooleanField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
        ),
    ]
