# Generated by Django 5.1.6 on 2025-02-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='content',
            field=models.TextField(default='Default Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tools',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
