# Generated by Django 5.1.6 on 2025-02-08 17:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tools_content_tools_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tools',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='intro',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
    ]
