# Generated by Django 5.1.6 on 2025-02-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_tools_meta_description_tools_modified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='custom_header_html',
        ),
        migrations.AddField(
            model_name='tools',
            name='custom_footer_html',
            field=models.TextField(blank=True, help_text='Add custom CSS/Javascript for footer', null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='custom_body_html',
            field=models.TextField(blank=True, help_text='Add custom HTML/Javascript for header', null=True),
        ),
    ]
