# Generated by Django 5.1.6 on 2025-02-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_alter_tools_content_alter_tools_intro_and_more'),
    ]

    operations = [
    ]
